force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Dept_no__c.field-meta.xml
<CustomField>
    <fullName>Dept_no__c</fullName>
    <label>Dept no</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>Employee Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeInsert.cls
public class EmployeeInsert {

    public String job { get; set; }

    public integer dept { get; set; }

    public integer salary { get; set; }

    public String ename { get; set; }

    public PageReference cancel() {
        return null;
    }


    public PageReference insert_record() {
        Employee__c emp = new Employee__c();
        emp.ename__c = ename;
        emp.salary__c = salary;
        emp.dept_no__c = dept;
        emp.designation__c = job;
        insert emp;
        
       
        return null;
    }

}