force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>EMP-{0000}</displayFormat>
        <label>Employee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Dept_no__c.field-meta.xml
<CustomField>
    <fullName>Dept_no__c</fullName>
    <label>Dept no</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>Employee Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getEmployee.cls
public class getEmployee {

    public String job { get; set; }

    public decimal dept { get; set; }

    public decimal salary { get; set; }

    public String ename { get; set; }

    public String empid { get; set; }

    public PageReference cancel() {
        return null;
    }


    public PageReference get_record() {
        Employee__c emp = new Employee__c();
        emp = [select name, ename__c, salary__c, designation__c, dept_no__c from employee__c where name like :empid];
        ename = emp.ename__c;
        salary = emp.salary__c;
        dept = emp.dept_no__c;
        job = emp.designation__c;
        return null;
    }

}